name: Uncrustify

on: 
  issue_comment
    types: [created]

jobs:
  run_uncrustify:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'fix the style')
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
            path: repo
            ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Style
        run: | 
          cd repo
          # find . \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) -exec uncrustify -c uncrustify.cfg --check {} +
          find . \( -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" \) -exec uncrustify -c uncrustify.cfg --replace --no-backup {} +
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -am "Uncrustified"
          git push

